INSERT INTO characters
VALUES /*CHARACTER ID, NAME, BIRTH YEAR, GENDER, HAIR COLOR, DEBUT SEASON*/
    /*PART 1 CHARACTERS*/
    (001, 'Jonathan Joestar', 1868, 'male', 'blue', 1),
    (002, 'Will Anthonio Zeppeli', 1838, 'male', 'brown', 1),
    (003, 'Robert E. O. Speedwagon', 1863, 'male', 'blond', 1),
    (004, 'Erina Joestar', 1869, 'female', 'blonde', 1),
    (005, 'Poco', NULL, 'male', 'brown', 1),
    (006, 'George Joestar I', NULL, 'male', 'blue', 1),
    (007, 'Tonpetty', NULL, 'male', 'white', 1),
    (008, 'Straizo', 1863, 'male', 'black', 1),
    (009, 'Dire', NULL, 'male', 'blond', 1),
    (010, 'Dio Brando', 1867, 'male', 'blond', 1),
    (011, 'Wang Chan', 1500, 'male', 'black', 1),
    (012, 'Jack the Ripper', NULL, 'male', 'auburn', 1),
    (013, 'Tarkus', 1500, 'male', 'auburn', 1),
    (014, 'Bruford', 1500, 'male', 'black', 1),
    (015, 'Dario Brando', 1827, 'male', 'white', 1),
    /*PART 2 CHARACTERS*/
    (016, 'Joseph Joestar', 1920, 'male', 'brown', 2),
    (017, 'Ceasar Anthonio Zeppeli', 1918, 'male', 'blond', 2),
    (018, 'Lisa Lisa', 1888, 'female', 'brown', 2),
    (019, 'Rudol von Stroheim', NULL, 'male', 'blond', 2),
    (020, 'Messina', NULL, 'male', 'black', 2),
    (021, 'Loggins', NULL, 'male', 'black', 2),
    (022, 'Smokey Brown', NULL, 'male', 'black', 2),
    (023, 'Suzi Q', NULL, 'female', 'blonde', 2),
    (024, 'Kars', -100000, 'male', 'purple', 2),
    (025, 'Esidisi', -90000, 'male', 'white', 2),
    (026, 'Wamuu', -10000, 'male', 'blond', 2),
    (027, 'Santana', -8000, 'male', 'red', 2),
    (028, 'Donovan', NULL, 'male', 'red', 2),
    (029, 'Wired Beck', NULL, 'male', 'brown', 2),
    (030, 'Mark', NULL, 'male', 'brown', 2),
    (031, 'Mario Zeppeli', NULL, 'male', 'black', 2),
    (032, 'George Joestar II', 1889, 'male', 'brown', 2),
    /*PART 3 CHARACTERS*/
    (033, 'Jotaro Kujo', 1970, 'male', 'black', 3),
    (034, 'Muhammad Avdol', 1960, 'male', 'black', 3),
    (035, 'Noriaki Kakyoin', 1971, 'male', 'red', 3),
    (036, 'Jean Pierre Polnareff', 1965, 'male', 'white', 3),
    (037, 'Iggy', NULL, 'male', 'black/white', 3),
    (038, 'Holy Kujo', 1942, 'female', 'blonde', 3),
    (039, 'Anne', NULL, 'female', 'black', 3),
    (040, 'Roses', NULL, 'male', 'gray', 3),
    (041, 'Enyaba', NULL, 'female', 'gray', 3),
    (042, 'Vanilla Ice', NULL, 'male', 'brown', 3),
    (043, 'Hol Horse', NULL, 'male', 'blond', 3),
    (044, 'Nukesaku', NULL, 'male/female', 'black', 3),
    (045, 'Daniel J. D`Arby', 1957, 'male', 'black', 3),
    (046, 'Pet Shop', NULL, 'male', 'brown', 3),
    (047, 'N`Doul', NULL, 'male', 'black', 3),
    (048, 'Mariah', NULL, 'female', 'white', 3),
    (049, 'Alessi', 1950, 'male', 'brown', 3),
    (050, 'Oingo', NULL, 'male', 'black', 3),
    (051, 'Boingo', NULL, 'male', 'black', 3),
    (052, 'Anubis', NULL, NULL, 'male', NULL, 3),
    (053, 'Terence T. D`Arby', 1968, 'male', 'green', 3),
    (054, 'Billie Jean', NULL, 'male', 'black', 3),
    (055, 'Gray Fly', NULL, 'male', 'white', 3),
    (056, 'Captain Tennille', NULL, 'male', 'blond', 3),
    (057, 'Forever', NULL, 'male', 'brown', 3),
    (058, 'Devo', NULL, 'male', 'brown', 3),
    (059, 'Rubber Soul', NULL, 'male', 'black', 3),
    (060, 'Centerfold', NULL, 'male', 'bald', 3),
    (061, 'Nena', NULL, 'female', 'black', 3),
    (062, 'ZZ', NULL, 'male', 'black', 3),
    (063, 'Steely Dan', NULL, 'male', 'black', 3),
    (064, 'Arabia Fats', NULL, 'male', 'brown', 3),
    (065, 'Mannish Boy', 1988, 'male', 'black', 3),
    (066, 'Cameo', NULL, 'male', 'brown', 3),
    (067, 'Midler', NULL, 'female', 'brown', 3),
    /*PART 4 CHARACTERS*/
    (068, 'Josuke Higashikata', 1983, 'male', 'black', 4),
    (069, 'Okuyasu Nijimura', 1983, 'male', 'black', 4),
    (070, 'Koichi Hirose', 1984, 'male', 'gray', 4),
    (071, 'Rohan Kishibe', 1979, 'male', 'green', 4),
    (072, 'Hayato Kawajiri', 1988, 'male', 'orange', 4),
    (073, 'Reimi Sugimoto', 1976, 'female', 'pink', 4),
    (074, 'Shigekiyo Yangu', 1986, 'male', 'bald', 4),
    (075, 'Mikitaka Hazekura', 1783, 'male', 'blond', 4),
    (076, 'Yukako Yamagishi', NULL, 'female', 'purple', 4),
    (077, 'Yuya Fungami', NULL, 'male', 'black/white', 4),
    (078, 'Tamami Kobayashi', 1979, 'male', 'black', 4),
    (079, 'Toshikazu hazamada', 1981, 'male', 'black', 4),
    (080, 'Tonio Trussardi', 1970, 'male', 'brown', 4),
    (081, 'Aya Tsuji', NULL, 'female', 'blonde', 4),
    (082, 'Tomoko Higashikata', 1962, 'female', 'black', 4),
    (083, 'Ryohei Higashikata', 1944, 'male', 'gray', 4),
    (084, 'Shinobu Kawajiri', NULL, 'female', 'pink', 4),
    (085, 'Yoshikage Kira', 1966, 'male', 'blond', 4),
    (086, 'Yoshihiro Kira', NULL, 'male', 'gray', 4),
    (087, 'Tama the Cat', NULL, NULL, 'gray', 4),
    (088, 'Keicho Nijimura', 1981, 'male', 'blond', 4),
    (089, 'Akira Otoishi', 1979, 'male', 'purple', 4),
    (090, 'Angelo Katagiri', 1964, 'male', 'gray', 4),
    (091, 'Ken Oyanagi', 1988, 'male', 'white', 4),
    (092, 'Toyohiro Kanedaichi', NULL, 'male', 'red', 4),
    (093, 'Terunosuke Miyamoto', NULL, 'male', 'white', 4),
    (094, 'Masazo Kinoto', 1970, 'male', 'orange', 4),
    (095, 'Two Rats', NULL, NULL, 'brown', 4),
    /*PART 5 CHARACTERS*/
    (096, 'Giorno Giovanna', 1985, 'male', 'blond', 5),
    (097, 'Bruno Bucciarati', 1980, 'male', 'black', 5),
    (098, 'Leone Abbacchio', 1980, 'male', 'white', 5),
    (099, 'Guido Mista', 1982, 'male', NULL, 5),
    (100, 'Narancia', 1983, 'male', 'black', 5),
    (101, 'Pannacotta Fugo', 1985, 'male', 'orange', 5),
    (102, 'Trish Una', 1985, 'male', 'pink', 5),
    (103, 'Coco Jumbo the Turtle', NULL, 'male', 'bald', 5),
    (104, 'Pericolo', NULL, 'male', 'gray', 5),
    (105, 'Diavolo', 1967, 'male', 'pink', 5),
    (106, 'Vinegar Dopio', 1967, 'male', 'pink', 5),
    (107, 'Squalo', NULL, 'male', 'orange', 5),
    (108, 'Tiziano', NULL, 'male', 'blond', 5),
    (109, 'Carne', NULL, 'male', 'pink', 5),
    (110, 'Cioccolata', 1967, 'male', 'green', 5),
    (111, 'Secco', NULL, 'male', 'bald', 5),
    (112, 'Polpo', NULL, 'male', 'bald', 5),
    (113, 'Mario Zucchero', 1976, 'male', 'green', 5),
    (114, 'Sale', NULL, 'male', 'orange', 5),
    (115, 'Risotto Nero', 1974, 'male', 'gray', 5),
    (116, 'Formaggio', NULL, 'male', 'gray', 5),
    (117, 'Illuso', NULL, 'male', 'brown', 5),
    (118, 'Prosciutto', NULL, 'male', 'blond', 5),
    (119, 'Pesci', NULL, 'male', 'green', 5),
    (120, 'Melone', NULL, 'male', 'purple', 5),
    (121, 'Ghiaccio', NULL, 'male', 'blue', 5),
    (122, 'Scolippi', NULL, 'male', 'purple', 5);

INSERT INTO stands
VALUES/*STAND ID, CHARACTER ID, NAME, RANGE TYPE, ABILITY TYPE, FORM TYPE, SPECIAL TYPE*/
    /*PART 3 STANDS*/
    (001, 033, 'Star Platinum', 'close', 'reconnaissance', 'natural humanoid', NULL),
    (002, 034, 'Magicians Red', 'close', 'reconnaissance', 'natural humanoid', NULL),
    (003, 016, 'Hermit Purple', 'close', 'reconnaissance', 'natural non-humanoid', NULL),
    (004, 035, 'Hierophant Green', 'long', 'reconnaissance', 'artificial humanoid', NULL),
    (005, 036, 'Silver Chariot', 'close', NULL, 'artificial humanoid', NULL),
    (006, 037, 'The Fool', 'close', 'materialized', 'artificial non-humanoid', NULL),
    (007, 010, 'The World', 'close', 'range irrelevant', 'natural-humanoid', NULL),
    (008, 055, 'Tower of Gray', 'long', NULL, 'natural non-humanoid', NULL),
    (009, 056, 'Dark Blue Moon', 'close', NULL, 'natural non-humanoid', NULL),
    (010, 057, 'Strength', 'close', 'materialized', 'artificial non-humanoid', NULL),
    (011, 058, 'Ebony Devil', 'long', 'materialized', 'natural non-humanoid', NULL),
    (012, 059, 'Yellow Temperance', 'close', 'materialized', 'natural non-humanoid', NULL),
    (013, 060, 'Hanged Man', 'long', NULL, 'natural non-humanoid', NULL),
    (014, 043, 'Emperor', 'close', NULL, 'artificial non-humanoid', NULL),
    (015, 061, 'Empress', 'long', 'materialized', 'natural humanoid', NULL),
    (016, 062, 'Wheel of Fortune', 'close', 'materialized', 'artificial non-humanoid', NULL),
    (017, 041, 'Justice', 'long', NULL, 'natural non-humanoid', NULL),
    (018, 063, 'Lovers', 'long', NULL, 'natural humanoid', NULL),
    (019, 064, 'Sun', 'long', NULL, 'natural non-humanoid', NULL),
    (020, 065, 'Death Thirteen', 'close', 'psychological assault', 'artificial humanoid', NULL),
    (021, 066, 'Judgement', 'close', NULL, 'artificial humanoid', NULL),
    (022, 067, 'High Priestess', 'long', NULL, 'natural humanoid', NULL),
    (023, 047, 'Geb', 'long', 'materialized', 'natural non-humanoid', NULL),
    (024, 050, 'Khnum', NULL, 'range irrelevant', 'phenomenon', NULL),
    (025, 051, 'Tohth', 'automatic', 'foresight', 'artificial non-humanoid', NULL),
    (026, 052, 'Anubis', 'automatic', 'psychological assault', 'artifical non-humanoid', 'shared/sentient'),
    (027, 048, 'Bastet', 'long', NULL, 'artificial non-humanoid', NULL),
    (028, 049, 'Sethan', 'close', 'materialized', 'natural non-humanoid', NULL),
    (029, 045, 'Osiris', 'close', 'psychological assault', 'natural humanoid', NULL),
    (030, 046, 'Horus', 'close', NULL, 'natural non-humanoid', NULL),
    (031, 053, 'Atum', 'close', 'psychological assault', 'artificial humanoid', NULL),
    (032, 054, 'Tenore Sax', NULL, 'psychological assault', 'phenomenon', NULL),
    (033, 042, 'Cream', 'close', NULL, 'natural humanoid', NULL),
    /*PART 4 STANDS*/
    (034, 068, 'Crazy Diamond', 'close', NULL, 'natural humanoid', NULL),
    (035, 069, 'The Hand', 'close', NULL, 'artificial-humanoid', NULL),
    (036, 070, 'Echoes ACT 1', 'long', 'psychological assault', 'natural non-humanoid', 'evolved'),
    (037, 070, 'Echoes ACT 2', 'long', NULL, 'artificial humanoid', 'evolved'),
    (038, 070, 'Echoes ACT 3', 'close', NULL, 'artificial humanoid', 'evolved'),
    (039, 071, 'Heavens Door', 'close', 'reconnaissance', 'natural humanoid', NULL),
    (041, 076, 'Love Deluxe', NULL, 'range irrelevant', 'phenomenon', NULL),
    (042, 074, 'Harvest', 'long', 'reconnaissance', 'natural non-humanoid', 'colony'),
    (043, 085, 'Killer Queen', 'close', NULL, 'natural humanoid', 'evolved'),
    (044, 085, 'Killer Queen Sheer Heart Attack', 'automatic', NULL, 'artificial non-humanoid', 'evolved'),
    (045, 085, 'Killer Queen Bites the Dust', 'automatic', 'psychological assault', 'natural humanoid', 'evolved'),
    (046, 090, 'Aqua Necklace', 'long', 'materialized', 'natural humanoid', NULL),
    (047, 088, 'Bad Company', 'close', 'reconnaissance', 'natural humanoid', 'colony'),
    (048, 089, 'Red Hot Chili Pepper', 'long', NULL, 'natural humanoid', NULL),
    (049, 078, 'The Lock', NULL, 'psychological assault', 'artificial non-humanoid', NULL),
    (050, 079, 'Surface', 'automatic', 'materialized', 'phenomenon', 'sentient'),
    (051, 080, 'Pearl Jam', NULL, 'range irrelevant', 'natural non-humanoid', 'colony'),
    (052, NULL, 'Achtung Baby', NULL, 'range irrelevant', 'phenomenon', NULL),
    (053, NULL, 'Ratt', 'close', NULL, 'artificial non-humanoid', 'shared'),
    (054, 081, 'Cinderella', 'close', NULL, 'artificial humanoid', NULL),
    (055, 086, 'Atom Heart Father', NULL, 'materialized', 'phenomenon', NULL),
    (056, 091, 'Boy II Man', 'close', 'psychological assault', 'artificial humanoid', NULL),
    (057, 075, 'Earth Wind and Fire', NULL, 'range irrelevent', 'phenomenon', NULL),
    (058, 077, 'Highway Star', 'automatic', 'reconnaissance', 'natural humanoid', NULL),
    (059, 087, 'Stray Cat', NULL, 'materialized', 'phenomenon', 'sentient'),
    (060, 092, 'Superfly', 'automatic', 'materialized', 'artificial non-humanoid', NULL),
    (061, 093, 'Enigma', 'close', 'psychological assault', 'artificial humanoid', NULL),
    (062, 094, 'Cheap Trick', 'automatic', 'psychological assault', 'natural humanoid', 'shared/sentient'),
    /*PART 5 STANDS*/
    (063, 096, 'Gold Experience', 'close', 'reconnaissance', 'natural humanoid', NULL),
    (064, 097, 'Sticky Fingers', 'close', NULL, 'natural humanoid', NULL),
    (065, 098, 'Moody Blues', 'close', 'reconnaissance', 'artificial humanoid', NULL),
    (066, 099, 'Sex Pistols', 'long', NULL, 'natural humanoid', 'colony/sentient'),
    (067, 100, 'Aerosmith', 'long', 'reconnaissance', 'artificial non-humanoid', NULL),
    (068, 101, 'Purple Haze', 'close', NULL, 'natural humanoid', NULL),
    (069, 102, 'Spice Girl', 'close', NULL, 'natural humanoid', 'sentient'),
    (070, 036, 'Chariot Requiem', 'automatic', NULL, 'natural humanoid', 'evolved'),
    (071, 096, 'Gold Experience Requiem', 'close', 'range irrelevant', 'natural humanoid', 'evolved'),
    (072, 105, 'King Crimson', 'close', 'foresight', 'natural humanoid', 'shared'),
    (073, 112, 'Black Sabbath', 'automatic', NULL, 'artificial humanoid', NULL),
    (074, 113, 'Soft Machine', 'close', NULL, 'artificial humanoid', NULL),
    (075, 114, 'Kraft Work', 'close', NULL, 'artificial humanoid', NULL),
    (076, 116, 'Little Feet', 'close', NULL, 'artificial humanoid', NULL),
    (077, 117, 'Man in the Mirror', 'close', NULL, 'natural humanoid', NULL),
    (078, 103, 'Mr. President', NULL, 'range irrelevant', 'phenomenon', NULL),
    (079, 119, 'Beach Boy', 'close', 'reconnaissance', 'artificial non-humanoid', NULL),
    (080, 118, 'The Grateful Dead', 'close', NULL, 'artificial humanoid', NULL),
    (081, 120, 'Baby Face', 'automatic', 'materialized', 'artificial non-humanoid', 'sentient'),
    (082, 121, 'White Album', 'close', NULL, 'phenomenon', NULL),
    (083, 107, 'Clash', 'long', NULL, 'natural non-humanoid', NULL),
    (084, 108, 'Talking Head', 'long', NULL, 'natural non-humanoid', NULL),
    (085, 109, 'Notorious B.I.G.', 'automatic', NULL, 'phenomenon', NULL),
    (086, 115, 'Metallica', 'close', NULL, 'phenomenon', 'colony'),
    (087, 110, 'Green Day', 'close', NULL, 'artificial humanoid', NULL),
    (088, 111, 'Oasis', 'close', NULL, 'phenomenon', NULL),
    (089, 122, 'Rolling Stones', 'automatic', 'foresight', 'natural non-humanoid', NULL);
    
    

INSERT INTO namesakes
VALUES /*REFFERENCE, CHARACTER ID, STAND ID, SONG, ALBUM, ARTIST, GENRE*/
    /*PART 1 NAMESAKES*/
    ('Will Anthonio Zeppeli', 002, NULL, NULL, NULL, 'Led Zeppelin', 'rock'),
    ('Robert E.O. Speedwagon', 003, NULL, NULL, NULL, 'REO Speedwagon', 'rock'),
    ('Poco', 005, NULL, NULL, NULL, 'poco', 'country rock'),
    ('Tonpetty', 007, NULL, NULL, NULL, 'Tom Petty', 'rock'),
    ('Straizo', 008, NULL, NULL, NULL, 'Dire Straits', 'rock'),
    ('Dire', 009, NULL, NULL, NULL, 'Dire Straits', 'rock'),
    ('Dio Brando', 010, NULL, NULL, NULL, 'DIO', 'heavy metal'),
    ('Wang Chan', 011, NULL, NULL, NULL, 'Wang Chung', 'new wave'),
    ('Tarkus', 013, NULL, NULL, 'Tarkus', 'Emerson, Lake & Palmer', 'progressive rock'),
    ('Bruford', 014, NULL, NULL, NULL, 'Bill Bruford', 'progressive rock'),
    /*PART 2 NAMESAKES*/
    ('Lisa Lisa', 018, NULL, NULL, NULL, 'Lisa Lisa and Cult Jam', 'freestyle'),
    ('Messina', 020, NULL, NULL, NULL, 'Loggins and Messina', 'rock pop'),
    ('Loggins', 021, NULL, NULL, NULL, 'Loggins and Messina', 'rock pop'),
    ('Smokey Brown', 022, NULL, NULL, NULL, 'James Brown', 'funk'),
    ('Smokey Brown', 022, NULL, NULL, NULL, 'Smokey Robinson', 'r&b'),
    ('Suzi Q', 023, NULL, 'Suzie Q', NULL, 'Dale Hawkins', 'rockabilly'),
    ('Kars', 024, NULL, NULL, NULL, 'The Cars', 'rock'),
    ('Esidisi', 025, NULL, NULL, NULL, 'AC/DC', 'hard rock'),
    ('Wamuu', 026, NULL, NULL, NULL, 'Wham!', 'pop'),
    ('Santana', 027, NULL, NULL, NULL, 'Santana', 'latin rock'),
    ('Donovan', 028, NULL, NULL, NULL, 'Donovan', 'folk rock'),
    ('Wired Beck', 029, NULL, NULL, 'wired', 'Jeff Beck', 'rock'),
    /*PART 3 CHARACTER NAMESAKES*/
    ('Muhammad Avdol', 034, NULL, NULL, NULL, 'Paula Abdul', 'r&b'),
    ('Jean Pierre Polnareff', 036, NULL, NULL, NULL, 'Michel Polnareff', 'folk rock'),
    ('Iggy', 037, NULL, NULL, NULL, 'Iggy Pop', 'rock'),
    ('Roses', 040, NULL, NULL, NULL, 'Guns N Roses', 'hard rock'),
    ('Enyaba', 041, NULL, NULL, NULL, 'Enya', 'celtic'),
    ('Vanilla Ice', 042, NULL, NULL, NULL, 'Vanilla Ice', 'rap'),
    ('Hol Horse', 043, NULL, NULL, NULL, 'Hall & Oates', 'pop rock'),
    ('Daniel J. D`Arby', 045, NULL, NULL, NULL, 'Terence Trent D`Arby', 'pop'),
    ('Telence T. D`Arby', 053, NULL, NULL, NULL, 'Terence Trent D`Arby', 'pop'),
    ('Pet Shop', 46, NULL, NULL, NULL, 'Pet Shop Boys', 'synth pop'),
    ('N`Doul', 047, NULL, NULL, NULL, 'Youssou N`Dour', 'mbalax'),
    ('Mariah', 048, NULL, NULL, NULL, 'Mariah Carey', 'r&b'),
    ('Alessi', 049, NULL, NULL, NULL, 'Alessi Brothers', 'pop rock'),
    ('Oingo', 050, NULL, NULL, NULL, 'Oingo Boingo', 'ska'),
    ('Boingo', 051, NULL, NULL, NULL, 'Oingo Boingo', 'ska'),
    ('Billie Jean', 054, NULL, 'Billie Jean', 'Thriller', 'Michael Jackson', 'disco'),
    ('Gray Fly', 055, NULL, NULL, NULL, 'Glenn Frey', 'rock'),
    ('Captain Tennille', 056, NULL, NULL, NULL, 'Captain & Tennille', 'soft rock'),
    ('Forever', 057, NULL, NULL, 'Wu-Tang Forever', 'Wu-Tang Clan', 'hip hop'),
    ('Devo', 058, NULL, NULL, NULL, 'Devo', 'rock'),
    ('Rubber Soul', 059, NULL, NULL, 'Rubber Soul', 'The Beatles', 'folk rock'),
    ('Centerfold', 060, NULL, 'Centerfold', 'Freeze Frame', 'The J. Geils Band', 'power pop'),
    ('Nena', 061, NULL, NULL, NULL, 'Nena', 'neue deutsche welle'),
    ('ZZ', 062, NULL, NULL, NULL, 'ZZ Top', 'rock'),
    ('Steely Dan', 063, NULL, NULL, NULL, 'Steely Dan', 'rock'),
    ('Arabia Fats', 64, NULL, NULL, NULL, 'Fats Domino', 'rock and roll'),
    ('Mannish Boy', 065, NULL, 'Mannish Boy', NULL, 'Muddy Waters', 'chicago blues'),
    ('Cameo', 066, NULL, NULL, NULL, 'Cameo', 'r&b'),
    ('Midler', 067, NULL, NULL, NULL, 'Bette Midler', 'pop'),
    /*PART 3 STANDS*/
    ('Tower of Gray', NULL, 008, 'Fade to Grey', 'Visage', 'Visage', 'synth pop'),
    ('Dark Blue Moon', NULL, 009, 'Blue Moon', NULL, 'Richard Rodgers', 'ballad'),
    ('Cream', NULL, 033, NULL, NULL, 'Cream', 'rock'),
    /*PART 4 CHARACTERS*/
    ('Reimi Sugimoto', 073, NULL, 'See Emily Play', 'The Piper at the Gates of Dawn', 'Pink Floyd', 'rock'),
    /*PART 4 STANDS*/
    ('Crazy Diamond', NULL, 034, 'Shine On You Crazy Diamond', 'Wish You Were Here', 'Pink Floyd', 'progressive rock'),
    ('The Hand', NULL, 035, NULL, NULL, 'The Band', 'rock'),
    ('Echoes ACT 1', NULL, 036, 'Echoes', 'Meddle', 'Pink Floyd', 'progressive rock'),
    ('Echoes ACT 2', NULL, 037, 'Echoes', 'Meddle', 'Pink Floyd', 'progressive rock'),
    ('Echoes ACT 3', NULL, 038, 'Echoes', 'Meddle', 'Pink Floyd', 'progressive rock'),
    ('Heavens Door', NULL, 039, 'Knockin` on Heavens Door', 'Pat Garrett & Billy the Kid', 'Bob Dylan', 'folk rock'),
    ('Love Deluxe', NULL, 041, NULL, 'Love Deluxe', 'Sade', 'ambient'),
    ('Harvest', NULL, 042, NULL, 'Harvest', 'Neil Young', 'folk rock'),
    ('Killer Queen', NULL, 043, 'Killer Queen', 'Sheer Heart Attack', 'Queen', 'power pop'),
    ('Killer Queen Sheer Heart Attack', NULL, 044, NULL, 'Sheer Heart Attack', 'Queen', 'power pop'),
    ('Killer Queen Bites the Dust', NULL, 045, 'Another One Bites the Dust', 'The Game', 'Queen', 'funk rock'),
    ('Aqua necklace', NULL, 046, NULL, 'Aqua', 'Asia', 'progressive rock'),
    ('Bad Company', NULL, 047, NULL, NULL, 'Bad Company', 'hard rock'),
    ('Red Hot Chili Pepper', NULL, 048, NULL, NULL, 'Red Hot Chili Peppers', 'alternative rock'),
    ('The Lock', NULL, 049, 'The Rock', 'Quadrophenia', 'The Who', 'hard rock'),
    ('Surface', NULL, 050, NULL, NULL, 'Surface', 'pop'),
    ('Pearl Jam', NULL, 051, NULL, NULL, 'Pearl Jam', 'alternative rock'),
    ('Achtung Baby', NULL, 052, NULL, 'Achtung Baby', 'U2', 'alternative rock'),
    ('Ratt', NULL, 053, NULL, NULL, 'Ratt', 'heavy metal'),
    ('Cinderella', NULL, 054, NULL, NULL, 'Cinderella', 'glam metal'),
    ('Atom Heart Father', NULL, 055, NULL, 'Atom Heart Mother', 'Pink Floyd', 'progressive rock'),
    ('Boy II Man', NULL, 056, NULL, NULL, 'Boyz II Men', 'r&b'),
    ('Earth Wind and Fire', NULL, 057, NULL, NULL, 'Earth, Wind & Fire', 'r&b'),
    ('Highway Star', NULL, 058, 'Highway Star', 'Machine Head', 'Deep Purple', 'hard rock'),
    ('Stray Cat', NULL, 059, NULL, NULL, 'Stray Cats', 'rockabilly'),
    ('Super Fly', NULL, 060, NULL, 'Super Fly', 'Curtis Mayfield', 'soul'),
    ('Enigma', NULL, 061, NULL, NULL, 'Enigma', 'ambient'),
    ('Cheap Trick', NULL, 062, NULL, NULL, 'Cheap Trick', 'rock'),
    /*PART 5 CHARACTERS*/
    ('Coco Jumbo the Turtle', 103, NULL, 'Coco Jamboo', 'We See the Same Sun', 'Mr. President', 'eurodance'),
    ('Mario Zucchero', 113, NULL, NULL, NULL, 'Zucchero', 'blues'),
    /*PART 5 STANDS*/
    ('The Gold Experience', NULL, 063, NULL, 'The Gold Experience', 'Prince', 'funk rock'),
    ('Sticky Fingers', NULL, 062, NULL, 'Sticky Fingers', 'The Rolling Stones', 'hard rock'),
    ('Moody Blues', NULL, 065, NULL, NULL, 'The Moody Blues', 'progressive rock'),
    ('Sex Pistols', NULL, 066, NULL, NULL, 'Sex Pistols', 'punk rock'),
    ('Aerosmith', NULL, 067, NULL, NULL, 'Aerosmith', 'hard rock'),
    ('Purple Haze', NULL, 068, 'Purple Haze', 'The Jimi Hendrix Experience', 'Jimi Hendrix', 'psychedelic rock'),
    ('Spice Girl', NULL, 069, NULL, NULL, 'Spice Girls', 'pop'),
    ('Chariot Requiem', NULL, 070, 'Requiem', NULL, 'Mozart', 'classical'),
    ('Gold Experience Requiem', NULL, 071, 'Requiem', NULL, 'Mozart', 'classical'),
    ('King Crimson', NULL, 072, NULL, NULL, 'King Crimson', 'progressive rock'),
    ('Black Sabbath', NULL, 073, NULL, NULL, 'Black Sabbath', 'heavy metal'),
    ('Soft Machine', NULL, 074, NULL, NULL, 'Soft Machine', 'psychedelic rock'),
    ('Kraft Work', NULL, 075, NULL, NULL, 'Kraftwerk', 'electronic'),
    ('Little Feet', NULL, 076, NULL, NULL, 'Little Feat', 'country rock'),
    ('Man in the Mirror', NULL, 077, 'Man in the Mirror', 'Bad', 'Michael Jackson', 'pop'),
    ('Mr. President', NULL, 078, NULL, NULL, 'Mr. President', 'eurodance'),
    ('Beach Boy', NULL, 079, NULL, NULL, 'The Beach Boys', 'surf rock'),
    ('The Grateful Dead', NULL, 080, NULL, NULL, 'The Grateful Dead', 'rock'),
    ('Baby Face', NULL, 081, NULL, NULL, 'Babyface', 'r&b'),
    ('White Album', NULL, 082, NULL, 'White Album', 'The Beatles', 'rock'),
    ('Clash', NULL, 083, NULL, NULL, 'Clash', 'punk rock'),
    ('Talking Head', NULL, 084, NULL, NULL, 'Talking Heads', 'post punk'),
    ('Notorious B.I.G.', NULL, 085, NULL, NULL, 'Notorious B.I.G.', 'hip hop'),
    ('Metallica', NULL, 086, NULL, NULL, 'Metallica', 'heavy metal'),
    ('Green Day', NULL, 087, NULL, NULL, 'Green Day', 'punk rock'),
    ('Oasis', NULL, 088, NULL, NULL, 'Oasis', 'rock'),
    ('Rolling Stones', NULL, 089, NULL, NULL, 'The Rolling Stones', 'rock');

INSERT INTO seasons
VALUES/*SEASON NUMBER, SEASON TITLE, PROTAGONIST ID, ANTAGONIST ID, FIRST AIRED, LAST AIRED*/
    (1, 'Phantom Blood', 001, 010, 10-05-2012, 11-30-2012),
    (2, 'Battle Tendency', 016, 024, 12-07-2012, 04-05-2013),
    (3, 'Stardust Crusaders', 033, 010, 04-04-2014, 06-19-2015),
    (4, 'Diamond is Unbreakable', 068, 085, 04-01-2016, 12-23-2016),
    (5, 'Golden Wind', 096, 105, 10-05-2018, 07-28-2019);

INSERT INTO episodes
VALUES /*episodeID, seasonID, episode_name, air_date, intro_songID, outro_songID, primaryProtag, secondaryProtag, primaryAntag, secondaryAntag*/
    /*PART 1 EPISODES*/
    (001, 1, '', , NULL, 10, , , , ),
    (002, 1, '', , 01, 10, , , , ),
    (003, 1, '', , 01, 10, , , , ),
    (004, 1, '', , 01, 10, , , , ),
    (005, 1, '', , 01, 10, , , , ),
    (006, 1, '', , 01, 10, , , , ),
    (007, 1, '', , 01, 10, , , , ),
    (008, 1, '', , 01, 10, , , , ),
    (009, 1, '', , 01, 10, , , , ),
    /*PART 2 EPISODES*/
    (010, 2, '', , NULL, 10, , , , ),
    (011, 2, '', , 02, 10, , , , ),
    (012, 2, '', , 02, 10, , , , ),
    (013, 2, '', , 02, 10, , , , ),
    (014, 2, '', , 02, 10, , , , ),
    (015, 2, '', , 02, 10, , , , ),
    (016, 2, '', , 02, 10, , , , ),
    (017, 2, '', , 02, 10, , , , ),
    (018, 2, '', , 02, 10, , , , ),
    (019, 2, '', , 02, 10, , , , ),
    (020, 2, '', , 02, 10, , , , ),
    (021, 2, '', , 02, 10, , , , ),
    (022, 2, '', , 02, 10, , , , ),
    (023, 2, '', , 02, 10, , , , ),
    (024, 2, '', , 02, 10, , , , ),
    (025, 2, '', , 02, 10, , , , ),
    (026, 2, '', , 02, 02, , , , ),
    /*PART 3 EPISODES*/
    (027, 3, '', , NULL, NULL, , , ,),
    (028, 3, '', , 03, NULL, , , ,),
    (029, 3, '', , 03, 11, , , ,),
    (030, 3, '', , 03, 11, , , ,),
    (031, 3, '', , 03, 11, , , ,),
    (032, 3, '', , 03, 11, , , ,),
    (033, 3, '', , 03, 11, , , ,),
    (034, 3, '', , 03, NULL, , , ,),
    (035, 3, '', , 03, 11, , , ,),
    (036, 3, '', , 03, NULL, , , ,),
    (037, 3, '', , NULL, 11, , , ,),
    (038, 3, '', , NULL, 11, , , ,),
    (039, 3, '', , 03, 11, , , ,),
    (040, 3, '', , 03, 11, , , ,),
    (041, 3, '', , 03, 11, , , ,),
    (042, 3, '', , 03, 11, , , ,),
    (043, 3, '', , 03, 11, , , ,),
    (044, 3, '', , 03, 11, , , ,),
    (045, 3, '', , 03, 11, , , ,),
    (046, 3, '', , 03, 11, , , ,),
    (047, 3, '', , 03, 11, , , ,),
    (048, 3, '', , 03, 11, , , ,),
    (049, 3, '', , 03, 11, , , ,),
    (050, 3, '', , 03, 11, , , ,),
    (051, 3, '', , 04, 12, , , ,),
    (052, 3, '', , 04, 12, , , ,),
    (053, 3, '', , 04, 13, , , ,),
    (054, 3, '', , 04, 12, , , ,),
    (055, 3, '', , 04, 12, , , ,),
    (056, 3, '', , 04, 12, , , ,),
    (057, 3, '', , 04, 12, , , ,),
    (058, 3, '', , 04, 12, , , ,),
    (059, 3, '', , 04, 12, , , ,),
    (060, 3, '', , 04, 12, , , ,),
    (061, 3, '', , 04, 12, , , ,),
    (062, 3, '', , 04, 13, , , ,),
    (063, 3, '', , 04, 13, , , ,),
    (064, 3, '', , 04, 12, , , ,),
    (065, 3, '', , 04, 12, , , ,),
    (066, 3, '', , 04, 12, , , ,),
    (067, 3, '', , 04, NULL, , , ,),
    (068, 3, '', , 04, 12, , , ,),
    (069, 3, '', , 04, 12, , , ,),
    (070, 3, '', , 04, 12, , , ,),
    (071, 3, '', , 04, 12, , , ,),
    (072, 3, '', , 04, 12, , , ,),
    (073, 3, '', , 04, NULL, , , ,),
    (074, 3, '', , 04, 12, , , ,),
    /*PART 4 EPISODES*/
    (075, 4, '', , NULL, , , , ,),
    (076, 4, '', , 05, , , , ,),
    (077, 4, '', , 05, , , , ,),
    (078, 4, '', , 05, , , , ,),
    (079, 4, '', , 05, , , , ,),
    (080, 4, '', , 05, , , , ,),
    (081, 4, '', , 05, , , , ,),
    (082, 4, '', , 05, , , , ,),
    (083, 4, '', , 05, , , , ,),
    (084, 4, '', , NULL, , , , ,),
    (085, 4, '', , 05, , , , ,),
    (086, 4, '', , 05, , , , ,),
    (087, 4, '', , 05, , , , ,),
    (088, 4, '', , NULL, , , , ,),
    (089, 4, '', , 06, , , , ,),
    (090, 4, '', , 06, , , , ,),
    (091, 4, '', , NULL, , , , ,),
    (092, 4, '', , 06, , , , ,),
    (093, 4, '', , 06, , , , ,),
    (094, 4, '', , NULL, , , , ,),
    (095, 4, '', , 06, , , , ,),
    (096, 4, '', , 06, , , , ,),
    (097, 4, '', , 06, , , , ,),
    (098, 4, '', , 06, , , , ,),
    (099, 4, '', , NULL, , , , ,),
    (100, 4, '', , 06, , , , ,),
    (101, 4, '', , 07, , , , ,),
    (102, 4, '', , 07, , , , ,),
    (103, 4, '', , 07, , , , ,),
    (104, 4, '', , 07, , , , ,),
    (105, 4, '', , 07, , , , ,),
    (106, 4, '', , NULL, , , , ,),
    (107, 4, '', , 07, , , , ,),
    (108, 4, '', , 07, , , , ,),
    (109, 4, '', , 07, , , , ,),
    (110, 4, '', , 07, , , , ,),
    (111, 4, '', , 07, , , , ,),
    (112, 4, '', , 07, , , , ,),
    (113, 4, '', , 07, , , , ,),
    /*PART 5 EPISODES*/
    (114, 5, '', , NULL, , , , ,),
    (115, 5, '', , 08, , , , ,),
    (116, 5, '', , 08, , , , ,),
    (117, 5, '', , 08, , , , ,),
    (118, 5, '', , 08, , , , ,),
    (119, 5, '', , 08, , , , ,),
    (120, 5, '', , 08, , , , ,),
    (121, 5, '', , 08, , , , ,),
    (122, 5, '', , 08, , , , ,),
    (123, 5, '', , 08, , , , ,),
    (124, 5, '', , 08, , , , ,),
    (125, 5, '', , 08, , , , ,),
    (126, 5, '', , 08, , , , ,),
    (127, 5, '', , 08, , , , ,),
    (128, 5, '', , 08, , , , ,),
    (129, 5, '', , 08, , , , ,),
    (130, 5, '', , 08, , , , ,),
    (131, 5, '', , 08, , , , ,),
    (132, 5, '', , 08, , , , ,),
    (133, 5, '', , 08, , , , ,),
    (134, 5, '', , 08, , , , ,),
    (135, 5, '', , 09, , , , ,),
    (136, 5, '', , 09, , , , ,),
    (137, 5, '', , 09, , , , ,),
    (138, 5, '', , 09, , , , ,),
    (139, 5, '', , 09, , , , ,),
    (140, 5, '', , 09, , , , ,),
    (141, 5, '', , 09, , , , ,),
    (142, 5, '', , 09, , , , ,),
    (143, 5, '', , 09, , , , ,),
    (144, 5, '', , 09, , , , ,),
    (145, 5, '', , 09, , , , ,),
    (146, 5, '', , 09, , , , ,),
    (147, 5, '', , 09, , , , ,),
    (148, 5, '', , 09, , , , ,),
    (149, 5, '', , 09, , , , ,),
    (150, 5, '', , 09, , , , ,),
    (151, 5, '', , 09, , , , ,),
    (152, 5, '', , 09, , , , ,),

INSERT INTO songs
VALUES /*SONG ID, TITLE, ARTIST, RELEASE DATE*/
    /*INTRO SONGS*/
    (01, 'JoJo ~Sono Chi no Sadame~', 'Hiroaki "TOMMY" Tominaga', 11-21-2012),
    (02, 'BLOODY STREAM', 'Coda', 01-30-2013),
    (03, 'STAND PROUD', 'Jin Hashimoto', 04-23-2014),
    (04, 'JoJo Sono Chi no Kioku', 'JO STARS', 01-28-2015),
    (05, 'Crazy Noisy Bizarre Town', 'THE DU', 04-27-2016),
    (06, 'chase', 'batta', 07-27-2016),
    (07, 'Great Days', 'Karen Aoki & Daisuke Hasegawa', 10-19-2016),
    (08, 'Fighting Gold', 'Coda', 10-13-2018),
    (09, 'Uragirimono no Requiem', 'Daisuke Hasegawa', 03- 27-2019),
    /*OUTRO SONGS*/
    (10, 'Roundabout', 'Yes', 11-26-1971),
    (11, 'Walk Like an Egyptian', 'The Bangles', 01-02-1986),
    (12, 'Last Train Home', 'Pat Methany Group', 07-07-1987),
    (13, 'Akuyaku Kyosoyoku', 'Makoto Yasumura', 01-23-2015),
    (14, 'I Want You', 'Savage Garden', 05-27-1996),
    (15, 'Freek`n You', 'Jodeci', 05-30-1995),
    (16, 'Modern Crusaders', 'Enigma', 01-14-2000);
    
    