INSERT INTO characters
VALUES /*CHARACTER ID, NAME, BIRTH YEAR, GENDER, HAIR COLOR, DEBUT SEASON*/
    /*PART 1 CHARACTERS*/
    (001, 'Jonathan Joestar', 1868, 'male', 'blue', 1),
    (002, 'Will Anthonio Zeppeli', 1838, 'male', 'brown', 1),
    (003, 'Robert E. O. Speedwagon', 1863, 'male', 'blond', 1),
    (004, 'Erina Joestar', 1869, 'female', 'blonde', 1),
    (005, 'Poco', NULL, 'male', 'brown', 1),
    (006, 'George Joestar I', NULL, 'male', 'blue', 1),
    (007, 'Tonpetty', NULL, 'male', 'white', 1),
    (008, 'Straizo', 1863, 'male', 'black', 1),
    (009, 'Dire', NULL, 'male', 'blond', 1),
    (010, 'Dio Brando', 1867, 'male', 'blond', 1),
    (011, 'Wang Chan', 1500, 'male', 'black', 1),
    (012, 'Jack the Ripper', NULL, 'male', 'auburn', 1),
    (013, 'Tarkus', 1500, 'male', 'auburn', 1),
    (014, 'Bruford', 1500, 'male', 'black', 1),
    (015, 'Dario Brando', 1827, 'male', 'white', 1),
    /*PART 2 CHARACTERS*/
    (016, 'Joseph Joestar', 1920, 'male', 'brown', 2),
    (017, 'Ceasar Anthonio Zeppeli', 1918, 'male', 'blond', 2),
    (018, 'Lisa Lisa', 1888, 'female', 'brown', 2),
    (019, 'Rudol von Stroheim', NULL, 'male', 'blond', 2),
    (020, 'Messina', NULL, 'male', 'black', 2),
    (021, 'Loggins', NULL, 'male', 'black', 2),
    (022, 'Smokey Brown', NULL, 'male', 'black', 2),
    (023, 'Suzi Q', NULL, 'female', 'blonde', 2),
    (024, 'Kars', -100000, 'male', 'purple', 2),
    (025, 'Esidisi', -90000, 'male', 'white', 2),
    (026, 'Wamuu', -10000, 'male', 'blond', 2),
    (027, 'Santana', -8000, 'male', 'red', 2),
    (028, 'Donovan', NULL, 'male', 'red', 2),
    (029, 'Wired Beck', NULL, 'male', 'brown', 2),
    (030, 'Mark', NULL, 'male', 'brown', 2),
    (031, 'Mario Zeppeli', NULL, 'male', 'black', 2),
    (032, 'George Joestar II', 1889, 'male', 'brown', 2),
    /*PART 3 CHARACTERS*/
    (033, 'Jotaro Kujo', 1970, 'male', 'black', 3),
    (034, 'Muhammad Avdol', 1960, 'male', 'black', 3),
    (035, 'Noriaki Kakyoin', 1971, 'male', 'red', 3),
    (036, 'Jean Pierre Polnareff', 1965, 'male', 'white', 3),
    (037, 'Iggy', NULL, 'male', 'black/white', 3),
    (038, 'Holy Kujo', 1942, 'female', 'blonde', 3),
    (039, 'Anne', NULL, 'female', 'black', 3),
    (040, 'Roses', NULL, 'male', 'gray', 3),
    (041, 'Enyaba', NULL, 'female', 'gray', 3),
    (042, 'Vanilla Ice', NULL, 'male', 'brown', 3),
    (043, 'Hol Horse', NULL, 'male', 'blond', 3),
    (044, 'Nukesaku', NULL, 'male/female', 'black', 3),
    (045, 'Daniel J. D`Arby', 1957, 'male', 'black', 3),
    (046, 'Pet Shop', NULL, 'male', 'brown', 3),
    (047, 'N`Doul', NULL, 'male', 'black', 3),
    (048, 'Mariah', NULL, 'female', 'white', 3),
    (049, 'Alessi', 1950, 'male', 'brown', 3),
    (050, 'Oingo', NULL, 'male', 'black', 3),
    (051, 'Boingo', NULL, 'male', 'black', 3),
    (052, 'Anubis', NULL, NULL, 'male', NULL, 3),
    (053, 'Terence T. D`Arby', 1968, 'male', 'green', 3),
    (054, 'Billie Jean', NULL, 'male', 'black', 3),
    (055, 'Gray Fly', NULL, 'male', 'white', 3),
    (056, 'Captain Tennille', NULL, 'male', 'blond', 3),
    (057, 'Forever', NULL, 'male', 'brown', 3),
    (058, 'Devo', NULL, 'male', 'brown', 3),
    (059, 'Rubber Soul', NULL, 'male', 'black', 3),
    (060, 'Centerfold', NULL, 'male', 'bald', 3),
    (061, 'Nena', NULL, 'female', 'black', 3),
    (062, 'ZZ', NULL, 'male', 'black', 3),
    (063, 'Steely Dan', NULL, 'male', 'black', 3),
    (064, 'Arabia Fats', NULL, 'male', 'brown', 3),
    (065, 'Mannish Boy', 1988, 'male', 'black', 3),
    (066, 'Cameo', NULL, 'male', 'brown', 3),
    (067, 'Midler', NULL, 'female', 'brown', 3),
    /*PART 4 CHARACTERS*/
    (068, 'Josuke Higashikata', 1983, 'male', 'black', 4),
    (069, 'Okuyasu Nijimura', 1983, 'male', 'black', 4),
    (070, 'Koichi Hirose', 1984, 'male', 'gray', 4),
    (071, 'Rohan Kishibe', 1979, 'male', 'green', 4),
    (072, 'Hayato Kawajiri', 1988, 'male', 'orange', 4),
    (073, 'Reimi Sugimoto', 1976, 'female', 'pink', 4),
    (074, 'Shigekiyo Yangu', 1986, 'male', 'bald', 4),
    (075, 'Mikitaka Hazekura', 1783, 'male', 'blond', 4),
    (076, 'Yukako Yamagishi', NULL, 'female', 'purple', 4),
    (077, 'Yuya Fungami', NULL, 'male', 'black/white', 4),
    (078, 'Tamami Kobayashi', 1979, 'male', 'black', 4),
    (079, 'Toshikazu hazamada', 1981, 'male', 'black', 4),
    (080, 'Tonio Trussardi', 1970, 'male', 'brown', 4),
    (081, 'Aya Tsuji', NULL, 'female', 'blonde', 4),
    (082, 'Tomoko Higashikata', 1962, 'female', 'black', 4),
    (083, 'Ryohei Higashikata', 1944, 'male', 'gray', 4),
    (084, 'Shinobu Kawajiri', NULL, 'female', 'pink', 4),
    (085, 'Yoshikage Kira', 1966, 'male', 'blond', 4),
    (086, 'Yoshihiro Kira', NULL, 'male', 'gray', 4),
    (087, 'Tama the Cat', NULL, NULL, 'gray', 4),
    (088, 'Keicho Nijimura', 1981, 'male', 'blond', 4),
    (089, 'Akira Otoishi', 1979, 'male', 'purple', 4),
    (090, 'Angelo Katagiri', 1964, 'male', 'gray', 4),
    (091, 'Ken Oyanagi', 1988, 'male', 'white', 4),
    (092, 'Toyohiro Kanedaichi', NULL, 'male', 'red', 4),
    (093, 'Terunosuke Miyamoto', NULL, 'male', 'white', 4),
    (094, 'Masazo Kinoto', 1970, 'male', 'orange', 4),
    (095, 'Two Rats', NULL, NULL, 'brown', 4),
    /*PART 5 CHARACTERS*/
    (096, 'Giorno Giovanna', 1985, 'male', 'blond', 5),
    (097, 'Bruno Bucciarati', 1980, 'male', 'black', 5),
    (098, 'Leone Abbacchio', 1980, 'male', 'white', 5),
    (099, 'Guido Mista', 1982, 'male', NULL, 5),
    (100, 'Narancia', 1983, 'male', 'black', 5),
    (101, 'Pannacotta Fugo', 1985, 'male', 'orange', 5),
    (102, 'Trish Una', 1985, 'male', 'pink', 5),
    (103, 'Coco Jumbo the Turtle', NULL, 'male', 'bald', 5),
    (104, 'Pericolo', NULL, 'male', 'gray', 5),
    (105, 'Diavolo', 1967, 'male', 'pink', 5),
    (106, 'Vinegar Dopio', 1967, 'male', 'pink', 5),
    (107, 'Squalo', NULL, 'male', 'orange', 5),
    (108, 'Tiziano', NULL, 'male', 'blond', 5),
    (109, 'Carne', NULL, 'male', 'pink', 5),
    (110, 'Cioccolata', 1967, 'male', 'green', 5),
    (111, 'Secco', NULL, 'male', 'bald', 5),
    (112, 'Polpo', NULL, 'male', 'bald', 5),
    (113, 'Mario Zucchero', 1976, 'male', 'green', 5),
    (114, 'Sale', NULL, 'male', 'orange', 5),
    (115, 'Risotto Nero', 1974, 'male', 'gray', 5),
    (116, 'Formaggio', NULL, 'male', 'gray', 5),
    (117, 'Illuso', NULL, 'male', 'brown', 5),
    (118, 'Prosciutto', NULL, 'male', 'blond', 5),
    (119, 'Pesci', NULL, 'male', 'green', 5),
    (120, 'Melone', NULL, 'male', 'purple', 5),
    (121, 'Ghiaccio', NULL, 'male', 'blue', 5),
    (122, 'Scolippi', NULL, 'male', 'purple', 5);

INSERT INTO stands
VALUES/*STAND ID, CHARACTER ID, NAME, RANGE TYPE, ABILITY TYPE, FORM TYPE, SPECIAL TYPE*/
    /*PART 3 STANDS*/
    (001, 033, 'Star Platinum', 'close', 'reconnaissance', 'natural humanoid', NULL),
    (002, 034, 'Magicians Red', 'close', 'reconnaissance', 'natural humanoid', NULL),
    (003, 016, 'Hermit Purple', 'close', 'reconnaissance', 'natural non-humanoid', NULL),
    (004, 035, 'Hierophant Green', 'long', 'reconnaissance', 'artificial humanoid', NULL),
    (005, 036, 'Silver Chariot', 'close', NULL, 'artificial humanoid', NULL),
    (006, 037, 'The Fool', 'close', 'materialized', 'artificial non-humanoid', NULL),
    (007, 010, 'The World', 'close', 'range irrelevant', 'natural-humanoid', NULL),
    (008, 055, 'Tower of Gray', 'long', NULL, 'natural non-humanoid', NULL),
    (009, 056, 'Dark Blue Moon', 'close', NULL, 'natural non-humanoid', NULL),
    (010, 057, 'Strength', 'close', 'materialized', 'artificial non-humanoid', NULL),
    (011, 058, 'Ebony Devil', 'long', 'materialized', 'natural non-humanoid', NULL),
    (012, 059, 'Yellow Temperance', 'close', 'materialized', 'natural non-humanoid', NULL),
    (013, 060, 'Hanged Man', 'long', NULL, 'natural non-humanoid', NULL),
    (014, 043, 'Emperor', 'close', NULL, 'artificial non-humanoid', NULL),
    (015, 061, 'Empress', 'long', 'materialized', 'natural humanoid', NULL),
    (016, 062, 'Wheel of Fortune', 'close', 'materialized', 'artificial non-humanoid', NULL),
    (017, 041, 'Justice', 'long', NULL, 'natural non-humanoid', NULL),
    (018, 063, 'Lovers', 'long', NULL, 'natural humanoid', NULL),
    (019, 064, 'Sun', 'long', NULL, 'natural non-humanoid', NULL),
    (020, 065, 'Death Thirteen', 'close', 'psychological assault', 'artificial humanoid', NULL),
    (021, 066, 'Judgement', 'close', NULL, 'artificial humanoid', NULL),
    (022, 067, 'High Priestess', 'long', NULL, 'natural humanoid', NULL),
    (023, 047, 'Geb', 'long', 'materialized', 'natural non-humanoid', NULL),
    (024, 050, 'Khnum', NULL, 'range irrelevant', 'phenomenon', NULL),
    (025, 051, 'Tohth', 'automatic', 'foresight', 'artificial non-humanoid', NULL),
    (026, 052, 'Anubis', 'automatic', 'psychological assault', 'artifical non-humanoid', 'shared/sentient'),
    (027, 048, 'Bastet', 'long', NULL, 'artificial non-humanoid', NULL),
    (028, 049, 'Sethan', 'close', 'materialized', 'natural non-humanoid', NULL),
    (029, 045, 'Osiris', 'close', 'psychological assault', 'natural humanoid', NULL),
    (030, 046, 'Horus', 'close', NULL, 'natural non-humanoid', NULL),
    (031, 053, 'Atum', 'close', 'psychological assault', 'artificial humanoid', NULL),
    (032, 054, 'Tenore Sax', NULL, 'psychological assault', 'phenomenon', NULL),
    (033, 042, 'Cream', 'close', NULL, 'natural humanoid', NULL),
    /*PART 4 STANDS*/
    (034, 068, 'Crazy Diamond', 'close', NULL, 'natural humanoid', NULL),
    (035, 069, 'The Hand', 'close', NULL, 'artificial-humanoid', NULL),
    (036, 070, 'Echoes ACT 1', 'long', 'psychological assault', 'natural non-humanoid', 'evolved'),
    (037, 070, 'Echoes ACT 2', 'long', NULL, 'artificial humanoid', 'evolved'),
    (038, 070, 'Echoes ACT 3', 'close', NULL, 'artificial humanoid', 'evolved'),
    (039, 071, 'Heavens Door', 'close', 'reconnaissance', 'natural humanoid', NULL),
    (041, 076, 'Love Deluxe', NULL, 'range irrelevant', 'phenomenon', NULL),
    (042, 074, 'Harvest', 'long', 'reconnaissance', 'natural non-humanoid', 'colony'),
    (043, 085, 'Killer Queen', 'close', NULL, 'natural humanoid', 'evolved'),
    (044, 085, 'Killer Queen Sheer Heart Attack', 'automatic', NULL, 'artificial non-humanoid', 'evolved'),
    (045, 085, 'Killer Queen Bites the Dust', 'automatic', 'psychological assault', 'natural humanoid', 'evolved'),
    (046, 090, 'Aqua Necklace', 'long', 'materialized', 'natural humanoid', NULL),
    (047, 088, 'Bad Company', 'close', 'reconnaissance', 'natural humanoid', 'colony'),
    (048, 089, 'Red Hot Chili Pepper', 'long', NULL, 'natural humanoid', NULL),
    (049, 078, 'The Lock', NULL, 'psychological assault', 'artificial non-humanoid', NULL),
    (050, 079, 'Surface', 'automatic', 'materialized', 'phenomenon', 'sentient'),
    (051, 080, 'Pearl Jam', NULL, 'range irrelevant', 'natural non-humanoid', 'colony'),
    (052, NULL, 'Achtung Baby', NULL, 'range irrelevant', 'phenomenon', NULL),
    (053, NULL, 'Ratt', 'close', NULL, 'artificial non-humanoid', 'shared'),
    (054, 081, 'Cinderella', 'close', NULL, 'artificial humanoid', NULL),
    (055, 086, 'Atom Heart Father', NULL, 'materialized', 'phenomenon', NULL),
    (056, 091, 'Boy II Man', 'close', 'psychological assault', 'artificial humanoid', NULL),
    (057, 075, 'Earth Wind and Fire', NULL, 'range irrelevent', 'phenomenon', NULL),
    (058, 077, 'Highway Star', 'automatic', 'reconnaissance', 'natural humanoid', NULL),
    (059, 087, 'Stray Cat', NULL, 'materialized', 'phenomenon', 'sentient'),
    (060, 092, 'Superfly', 'automatic', 'materialized', 'artificial non-humanoid', NULL),
    (061, 093, 'Enigma', 'close', 'psychological assault', 'artificial humanoid', NULL),
    (062, 094, 'Cheap Trick', 'automatic', 'psychological assault', 'natural humanoid', 'shared/sentient'),
    /*PART 5 STANDS*/
    (063, 096, 'Golden Wind', 'close', 'reconnaissance', 'natural humanoid', NULL),
    (064, 097, 'Sticky Fingers', 'close', NULL, 'natural humanoid', NULL),
    (065, 098, 'Moody Blues', 'close', 'reconnaissance', 'artificial humanoid', NULL),
    (066, 099, 'Sex Pistols', 'long', NULL, 'natural humanoid', 'colony/sentient'),
    (067, 100, 'Aerosmith', 'long', 'reconnaissance', 'artificial non-humanoid', NULL),
    (068, 101, 'Purple Haze', 'close', NULL, 'natural humanoid', NULL),
    (069, 102, 'Spice Girl', 'close', NULL, 'natural humanoid', 'sentient'),
    (070, 036, 'Chariot Requiem', 'automatic', NULL, 'natural humanoid', 'evolved'),
    (071, 096, 'Gold Experience Requiem', 'close', 'range irrelevant', 'natural humanoid', 'evolved'),
    (072, 105, 'King Crimson', 'close', 'foresight', 'natural humanoid', 'shared'),
    (073, 112, 'Black Sabbath', 'automatic', NULL, 'artificial humanoid', NULL),
    (074, 113, 'Soft Machine', 'close', NULL, 'artificial humanoid', NULL),
    (075, 114, 'Kraft Work', 'close', NULL, 'artificial humanoid', NULL),
    (076, 116, 'Little Feet', 'close', NULL, 'artificial humanoid', NULL),
    (077, 117, 'Man in the Mirror', 'close', NULL, 'natural humanoid', NULL),
    (078, 103, 'Mr. President', NULL, 'range irrelevant', 'phenomenon', NULL),
    (079, 119, 'Beach Boy', 'close', 'reconnaissance', 'artificial non-humanoid', NULL),
    (080, 118, 'The Grateful Dead', 'close', NULL, 'artificial humanoid', NULL),
    (081, 120, 'Baby Face', 'automatic', 'materialized', 'artificial non-humanoid', 'sentient'),
    (082, 121, 'White Album', 'close', NULL, 'phenomenon', NULL),
    (083, 107, 'Clash', 'long', NULL, 'natural non-humanoid', NULL),
    (084, 108, 'Talking Head', 'long', NULL, 'natural non-humanoid', NULL),
    (085, 109, 'Notorious B.I.G.', 'automatic', NULL, 'phenomenon', NULL),
    (086, 115, 'Metallica', 'close', NULL, 'phenomenon', 'colony'),
    (087, 110, 'Green Day', 'close', NULL, 'artificial humanoid', NULL),
    (088, 111, 'Oasis', 'close', NULL, 'phenomenon', NULL),
    (089, 122, 'Rolling Stones', 'automatic', 'foresight', 'natural non-humanoid', NULL);
    
    

INSERT INTO characters
VALUES
    (),

INSERT INTO characters
VALUES
    (),

INSERT INTO characters
VALUES
    (),

INSERT INTO characters
VALUES
    (),
